export { defineTemplate, defineTemplateBase } from './core/define-template'
export { validateTemplateBase, validateTemplateData, validateTemplateDefinition } from './core/validation'
export type { TemplateFieldKind, ImageFieldScope, BaseFieldDescriptor, FieldDescriptor, TemplateAssetManifest, TemplateMeta, TemplateVariants } from './types'
export type { TextFieldDescriptor, TextareaFieldDescriptor, ColorFieldDescriptor, NumberFieldDescriptor, ImageFieldDescriptor } from './core/fields'
export type { TemplateBase, TemplateDefinition, TemplateRenderProps, InferTemplateData, TemplateContent, TemplateContentEntry } from './types'
export { fields } from './core/fields'
export { resolveTemplateData } from './core/resolve-template-data'
export type { TemplateDataValidationError } from './core/validation'
export { getVariants } from './core/get-variants'
export { getDefaultValues } from './core/get-default-values'
export { Markdown } from './markdown/markdown'
