export { defineTemplate, defineTemplateBase } from './core/define-template'
export { validateTemplateData, validateTemplateDefinition } from './core/validation'
export type { TemplateFieldKind, BaseFieldDescriptor, FieldDescriptor } from './types'
export type { TextFieldDescriptor, TextareaFieldDescriptor, ColorFieldDescriptor, UrlFieldDescriptor, NumberFieldDescriptor } from './core/fields'
export type { TemplateBase, TemplateDefinition, TemplateRenderProps, InferTemplateData } from './types'
export { fields } from './core/fields'
export { resolveTemplateData } from './core/resolve-template-data'
export type { TemplateDataValidationError } from './core/validation'
export { getLocales } from './core/get-locales'
export { getDefaultValues } from './core/get-default-values'
export { Markdown } from './markdown/markdown'
